#Generated by aw-scanner

ifeq ($(AW_CONVERTER),)
AW_CONVERTER:=aw-converter
endif

AW_SRCS:=tests/www/page1_html.c tests/www/page2_html.c tests/www/sub/sub_page1_html.c tests/www/sub/sub_page2_html.c tests/www/sub/sub_index_html.c tests/www/index_html.c 

tests/www/page1_html.c: tests/www/page1.html.aw tests/server_test.mk
	$(AW_CONVERTER) -o $@ -c page1_html $<

tests/www/page2_html.c: tests/www/page2.html.aw tests/server_test.mk
	$(AW_CONVERTER) -o $@ -c page2_html $<

tests/www/sub/sub_page1_html.c: tests/www/sub/page1.html.aw tests/server_test.mk
	$(AW_CONVERTER) -o $@ -c sub_page1_html $<

tests/www/sub/sub_page2_html.c: tests/www/sub/page2.html.aw tests/server_test.mk
	$(AW_CONVERTER) -o $@ -c sub_page2_html $<

tests/www/sub/sub_index_html.c: tests/www/sub/index.html.aw tests/server_test.mk
	$(AW_CONVERTER) -o $@ -c sub_index_html $<

tests/www/index_html.c: tests/www/index.html.aw tests/server_test.mk
	$(AW_CONVERTER) -o $@ -c index_html $<

