/*Generated by aw-converter*/

#include <atomweb.h>

typedef struct {
} AW_UserData;

static AW_Ptr aw_create (AW_Session *sess) {
	AW_Ptr ptr;
	AW_UserData *udata;
	udata = (AW_UserData*)malloc(sizeof(AW_UserData));
	ptr = (AW_Ptr)udata;
	return ptr;
}

static AW_Result aw_run (AW_Session *sess, AW_Ptr ptr) {
	AW_UserData *udata = (AW_UserData*)ptr;

#line 1 "tests/www/index.html.aw"
	aw_session_entity(sess, "<html>\n"
		"Welcome to Atom Web\n"
		"<form action=\"page1.html\">\n"
		"  <label for=\"name\">Name:</label>\n"
		"  <input type=\"text\" name=\"name\" id=\"name\" />\n"
		"  <br/>\n"
		"  <label for=\"male\">Male:</label>\n"
		"  <input type=\"checkbox\" name=\"male\" id=\"male\" />\n"
		"  <br/>\n"
		"  <label for=\"age\">Age:</label>\n"
		"  <input type=\"number\" name=\"age\" id=\"age\" />\n"
		"  <br/>\n"
		"  <input type=\"reset\" />\n"
		"  <input type=\"submit\" />\n"
		"</form>\n"
		"</html>\n"
		""
		, 387);
	udata = udata;
	return AW_OK;
}

static void aw_release (AW_Ptr data) {
	if (!data) return;
	free(data);
}

const AW_Class aw_index_html_class = {
	0,
	NULL,
	aw_create,
	aw_run,
	aw_release,
};

