/*Generated by aw-converter*/

#include <atomweb.h>

typedef struct {

#line 1 "tests/www/index.html.aw"

	int         id;
	const char *name;
} AW_UserData;

static AW_Ptr aw_create (AW_Session *sess) {
	AW_Ptr ptr;
	AW_UserData *udata;
	udata = (AW_UserData*)malloc(sizeof(AW_UserData));
	ptr = (AW_Ptr)udata;

#line 5 "tests/www/index.html.aw"

	udata->id = strtol(aw_session_get_param(sess, "id"), NULL, 0);
	udata->name = aw_session_get_param(sess, "name");
	return ptr;
}

static AW_Result aw_run (AW_Session *sess, AW_Ptr ptr) {
	AW_UserData *udata = (AW_UserData*)ptr;

#line 8 "tests/www/index.html.aw"
	aw_session_entity(sess, "\n"
		"<html>\n"
		""
		, 8);

#line 10 "tests/www/index.html.aw"
	aw_session_printf(sess,  "name:%s id:%d", udata->name, udata->id );

#line 10 "tests/www/index.html.aw"
	aw_session_entity(sess, "\n"
		"</html>\n"
		""
		, 9);
	udata = udata;
	return AW_OK;
}

static void aw_release (AW_Ptr data) {
	if (!data) return;
	free(data);
}

const AW_Class aw_index_html_class = {
	0,
	NULL,
	aw_create,
	aw_run,
	aw_release,
};

