/*Generated by aw-converter*/

#include <atomweb.h>


#line 1 "tests/www/page2.html.aw"

#include <sys/types.h>
#include <dirent.h>
typedef struct {
} AW_UserData;

static AW_Ptr aw_create (AW_Session *sess) {
	AW_Ptr ptr;
	AW_UserData *udata;
	udata = (AW_UserData*)malloc(sizeof(AW_UserData));
	ptr = (AW_Ptr)udata;
	return ptr;
}

static AW_Result aw_run (AW_Session *sess, AW_Ptr ptr) {
	AW_UserData *udata = (AW_UserData*)ptr;

#line 4 "tests/www/page2.html.aw"
	aw_session_entity(sess, "\n"
		"<html>\n"
		"\t"
		, 9);

#line 6 "tests/www/page2.html.aw"

	DIR *dir = opendir("/");
	struct dirent *ent;

	do {
		ent = readdir(dir);
		if (ent) {
	
#line 14 "tests/www/page2.html.aw"
	aw_session_printf(sess,  ent->d_name );

#line 15 "tests/www/page2.html.aw"
 if (ent->d_type == DT_DIR) 
#line 15 "tests/www/page2.html.aw"
	aw_session_entity(sess, "\n"
		"\t\t\t[DIR]\n"
		"\t\t<br/>\n"
		"\t"
		, 19);

#line 18 "tests/www/page2.html.aw"

		}
	} while (ent);
	closedir(dir);
	
#line 22 "tests/www/page2.html.aw"
	aw_session_entity(sess, "\n"
		"\t<button onclick=\"window.location.href=\'sub/\'\">next</button>\n"
		"</html>\n"
		""
		, 70);
	udata = udata;
	return AW_OK;
}

static void aw_release (AW_Ptr data) {
	if (!data) return;
	free(data);
}

const AW_Class aw_page2_html_class = {
	0,
	NULL,
	aw_create,
	aw_run,
	aw_release,
};

