/*Generated by aw-converter*/

#include <atomweb.h>


#line 1 "tests/www/page1.html.aw"

#include <time.h>
typedef struct {

#line 4 "tests/www/page1.html.aw"

	int age;
	int male;
	const char *name;
} AW_UserData;

static AW_Ptr aw_create (AW_Session *sess) {
	AW_Ptr ptr;
	AW_UserData *udata;
	udata = (AW_UserData*)malloc(sizeof(AW_UserData));
	ptr = (AW_Ptr)udata;

#line 9 "tests/www/page1.html.aw"

	const char *str;

	str = aw_session_get_param(sess, "age");
	udata->age = str ? strtol(str, NULL, 0) : 0;
	str = aw_session_get_param(sess, "male");
	udata->male = str ? 1 : 0;
	str = aw_session_get_param(sess, "name");
	udata->name = str ? str : "unknown";
	return ptr;
}

static AW_Result aw_run (AW_Session *sess, AW_Ptr ptr) {
	AW_UserData *udata = (AW_UserData*)ptr;

#line 18 "tests/www/page1.html.aw"
	aw_session_entity(sess, "\n"
		"<html>\n"
		"\t"
		, 9);

#line 20 "tests/www/page1.html.aw"

		time_t now;
		struct tm *date;
		int year;
	
#line 24 "tests/www/page1.html.aw"
	aw_session_entity(sess, "\n"
		"\tHello, "
		, 9);

#line 25 "tests/www/page1.html.aw"
	aw_session_printf(sess,  "%s",udata->name );

#line 25 "tests/www/page1.html.aw"
	aw_session_entity(sess, "\n"
		"\t<br/>\n"
		"\tHi,\n"
		"\t"
		, 14);

#line 28 "tests/www/page1.html.aw"
 if (udata->male) { 
#line 28 "tests/www/page1.html.aw"
	aw_session_entity(sess, "\n"
		"\t\tBoy\n"
		"\t"
		, 8);

#line 30 "tests/www/page1.html.aw"
 } else { 
#line 30 "tests/www/page1.html.aw"
	aw_session_entity(sess, "\n"
		"\t\tGirl\n"
		"\t"
		, 9);

#line 32 "tests/www/page1.html.aw"
 } 
#line 32 "tests/www/page1.html.aw"
	aw_session_entity(sess, "\n"
		"\t<br/>\n"
		"\n"
		"\t"
		, 10);

#line 35 "tests/www/page1.html.aw"

		time(&now);
		date = localtime(&now);
		year = date->tm_year - udata->age;
	
#line 39 "tests/www/page1.html.aw"
	aw_session_entity(sess, "\n"
		"\n"
		"\tYou were born in "
		, 20);

#line 41 "tests/www/page1.html.aw"
	aw_session_printf(sess,  "%d",year+1900 );

#line 41 "tests/www/page1.html.aw"
	aw_session_entity(sess, "\n"
		"\t<br/>\n"
		"\t<button onclick=\"window.location.href=\'page2.html\'\">next</button>\n"
		"</html>\n"
		""
		, 83);
	udata = udata;
	return AW_OK;
}

static void aw_release (AW_Ptr data) {
	if (!data) return;
	free(data);
}

const AW_Class aw_page1_html_class = {
	0,
	NULL,
	aw_create,
	aw_run,
	aw_release,
};

