/*Generated by aw-converter*/

#include <atomweb.h>

typedef struct {
} AW_UserData;

static AW_Ptr aw_create (AW_Session *sess) {
	AW_Ptr ptr;
	AW_UserData *udata;
	udata = (AW_UserData*)malloc(sizeof(AW_UserData));
	ptr = (AW_Ptr)udata;
	return ptr;
}

static AW_Result aw_run (AW_Session *sess, AW_Ptr ptr) {
	AW_UserData *udata = (AW_UserData*)ptr;

#line 1 "tests/www/sub/index.html.aw"
	aw_session_entity(sess, "<html>\n"
		"This is a sub directory\n"
		"<button onclick=\"window.location.href=\'page1.html\'\">next</button>\n"
		"</html>\n"
		""
		, 105);
	udata = udata;
	return AW_OK;
}

static void aw_release (AW_Ptr data) {
	if (!data) return;
	free(data);
}

const AW_Class aw_sub_index_html_class = {
	0,
	NULL,
	aw_create,
	aw_run,
	aw_release,
};

